### ISSUE TITLE
可以补充一下怎么回复导师的话术吗

### ISSUE THREAD

**Issue by lori-kuo** [yuezih/King-of-Pigeon#5]
套磁导师回复的期待夏令营交流再怎么回复啊？可以补充一下怎么回复导师的话术吗

**Comment by yuezih** [comment]
不用回复或者直接谢谢老师就行了？这不是官方回复嘛？我感觉等你入营或者拿了优营之后再去找老师就好了。
> “非常感谢您的回复！如有机会入营，我将全力以赴为学院的考核做好准备，争取有机会成为您的学生。”
